# -*- coding: utf-8 -*-
"""fase 4 - implementação ajustada resnet50 + xai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnT2C5pp8iTYqNccwo7IwEv-9r6lbIJq
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, applications
from sklearn.model_selection import GroupShuffleSplit
from google.colab import drive

drive.mount('/content/drive')

BASE_PATH = '/content/drive/MyDrive/MINI-DDSM/'
EXCEL_PATH = os.path.join(BASE_PATH, 'DataWMask.xlsx')
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
CHANNELS = 3
SEED = 42

df = pd.read_excel(EXCEL_PATH)

df['fullPath'] = df['fullPath'].str.replace('\\', '/', regex=False)
df['Tumour_Contour'] = df['Tumour_Contour'].str.replace('\\', '/', regex=False)

def extract_patient_id(path):
    parts = path.split('/')
    return parts[1] if len(parts) > 1 else 'unknown'

df['patient_id'] = df['fullPath'].apply(extract_patient_id)

class_map = {'Normal': 0, 'Benign': 1, 'Cancer': 2}
df['label'] = df['Status'].map(class_map)

gss_test = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
train_val_idx, test_idx = next(gss_test.split(df, df['label'], groups=df['patient_id']))

train_val_df = df.iloc[train_val_idx]
test_df = df.iloc[test_idx]

gss_val = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
train_idx, val_idx = next(gss_val.split(train_val_df, train_val_df['label'], groups=train_val_df['patient_id']))

train_df = train_val_df.iloc[train_idx]
val_df = train_val_df.iloc[val_idx]

print(f'Treino: {len(train_df)} | Val: {len(val_df)} | Teste: {len(test_df)}')

import numpy as np

def increase_brightness(img_array):
    return np.clip(img_array * 1.2, 0.0, 1.0).astype(np.float32)

def load_and_preprocess(path, label):
    full_path = tf.strings.join([BASE_PATH, path])
    img = tf.io.read_file(full_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0

    img = tf.numpy_function(increase_brightness, [img], tf.float32)
    img.set_shape([*IMG_SIZE, CHANNELS])

    return img, label

def create_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((dataframe['fullPath'].values, dataframe['label'].values))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

train_ds = create_ds(train_df)
val_ds = create_ds(val_df, shuffle=False)
test_ds = create_ds(test_df, shuffle=False)

base_model = applications.ResNet50(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model.trainable = True

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint = callbacks.ModelCheckpoint('best_model.keras', save_best_only=True, monitor='val_loss')

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=50,
    callbacks=[checkpoint]
)

import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento sem máscaras)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento sem máscaras)')
plt.legend()
plt.show()

test_loss, test_acc = model.evaluate(test_ds)
print(f'\nAcurácia no Teste (Treinamento sem máscaras): {test_acc:.4f}')

print("\nCalculando métricas detalhadas...")
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred_probs = model.predict(test_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\nRelatório de Classificação (Treinamento sem máscaras):")
target_names = ['Normal', 'Benign', 'Cancer']
print(classification_report(y_true, y_pred, target_names=target_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento sem máscaras)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

import cv2
import numpy as np

def get_gradcam_plus_plus(model, img_array, last_conv_layer_name):
    base_model = model.layers[0]
    last_conv_layer = base_model.get_layer(last_conv_layer_name)

    res_output = last_conv_layer.output

    x = model.layers[1](base_model.output)
    for layer in model.layers[2:]:
        x = layer(x)

    grad_model = tf.keras.models.Model([base_model.input], [res_output, x])

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        class_idx = tf.argmax(predictions[0])
        loss = predictions[:, class_idx]

    grads = tape.gradient(loss, conv_outputs)

    weights = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap = tf.reduce_sum(tf.multiply(weights, conv_outputs), axis=-1)

    heatmap = np.maximum(heatmap, 0) / (np.max(heatmap) + 1e-10)
    return heatmap[0]

def calculate_iou(y_true, y_pred):
    intersection = np.logical_and(y_true, y_pred)
    union = np.logical_or(y_true, y_pred)
    if np.sum(union) == 0: return 0
    return np.sum(intersection) / np.sum(union)

test_with_masks = test_df[(test_df['Status'] != 'Normal') & (test_df['Tumour_Contour'] != '-')]

num_samples_to_explain = min(20, len(test_with_masks))

if num_samples_to_explain > 0:
    sample_rows = test_with_masks.sample(num_samples_to_explain, random_state=SEED)

    fig, axes = plt.subplots(num_samples_to_explain, 3, figsize=(15, 4 * num_samples_to_explain))

    if num_samples_to_explain == 1:
        axes = np.expand_dims(axes, axis=0)

    for i, (_, row) in enumerate(sample_rows.iterrows()):
        img_path = os.path.join(BASE_PATH, row['fullPath'])
        mask_path = os.path.join(BASE_PATH, row['Tumour_Contour'])

        img_raw = tf.io.read_file(img_path)
        img_decoded = tf.image.decode_jpeg(img_raw, channels=3)
        img_resized = tf.image.resize(img_decoded, IMG_SIZE)
        img_normalized = tf.cast(img_resized, tf.float32) / 255.0
        img_batch = tf.expand_dims(img_normalized, 0)

        try:
            heatmap = get_gradcam_plus_plus(model, img_batch, 'conv5_block3_out')

            mask_img = cv2.imread(mask_path, 0)
            if mask_img is not None:
                mask = cv2.resize(mask_img, IMG_SIZE) > 0
                heatmap_resized = cv2.resize(heatmap, IMG_SIZE)
                heatmap_bin = heatmap_resized > 0.5
                iou_score = calculate_iou(mask, heatmap_bin)

                axes[i, 0].imshow(img_normalized)
                axes[i, 0].set_title(f'Imagem Original ({row["Status"]})')
                axes[i, 0].axis('off')

                axes[i, 1].imshow(mask, cmap='gray')
                axes[i, 1].set_title('Máscara Real (ROI)')
                axes[i, 1].axis('off')

                axes[i, 2].imshow(img_normalized)
                axes[i, 2].imshow(heatmap_resized, alpha=0.5, cmap='jet')
                axes[i, 2].set_title(f'Grad-CAM++ (IoU: {iou_score:.4f})')
                axes[i, 2].axis('off')
            else:
                print(f'Erro ao carregar o arquivo de máscara para a amostra {i+1}.')
        except Exception as e:
            print(f'Erro na execução do Grad-CAM++ para a amostra {i+1}: {e}')

    plt.tight_layout()
    plt.show()
else:
    print('Nenhuma amostra com máscara encontrada no conjunto de teste.')

import numpy as np
import matplotlib.pyplot as plt
import cv2

y_pred_probs = model.predict(test_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

test_df_eval = test_df.copy()
test_df_eval['pred'] = y_pred
test_df_eval['correct'] = test_df_eval['label'] == test_df_eval['pred']

valid_samples = test_df_eval[(test_df_eval['correct'] == True) &
                             (test_df_eval['Status'] != 'Normal') &
                             (test_df_eval['Tumour_Contour'] != '-')]

num_samples = min(20, len(valid_samples))
sample_df = valid_samples.sample(num_samples, random_state=SEED)

sample_images = []
sample_labels = []
sample_masks = []

for _, row in sample_df.iterrows():
    img_path = os.path.join(BASE_PATH, row['fullPath'])
    img_raw = tf.io.read_file(img_path)
    img_decoded = tf.image.decode_jpeg(img_raw, channels=3)
    img_resized = tf.image.resize(img_decoded, IMG_SIZE)
    img_normalized = tf.cast(img_resized, tf.float32) / 255.0
    sample_images.append(img_normalized.numpy())
    sample_labels.append(row['label'])

    mask_path = os.path.join(BASE_PATH, row['Tumour_Contour'])
    mask_raw = cv2.imread(mask_path, 0)
    if mask_raw is not None:
        mask_resized = cv2.resize(mask_raw, IMG_SIZE)
    else:
        mask_resized = np.zeros(IMG_SIZE)
    sample_masks.append(mask_resized)

sample_images = np.array(sample_images)
sample_labels = np.array(sample_labels)
sample_masks = np.array(sample_masks)
print(f'Selecionadas {len(sample_images)} imagens com máscaras para explicação.')

print("\nCalculando Grad-CAM Médio...")
average_heatmap = np.zeros(IMG_SIZE)
valid_heatmaps = 0

for i in range(len(sample_images)):
    img_batch = np.expand_dims(sample_images[i], 0)
    try:
        heatmap = get_gradcam_plus_plus(model, img_batch, 'conv5_block3_out')
        heatmap_resized = cv2.resize(heatmap, IMG_SIZE)
        average_heatmap += heatmap_resized
        valid_heatmaps += 1
    except Exception as e:
        print(f"Erro ao processar heatmap para amostra {i}: {e}")

if valid_heatmaps > 0:
    average_heatmap /= valid_heatmaps

    plt.figure(figsize=(6, 6))
    plt.imshow(average_heatmap, cmap='jet')
    plt.title(f'Grad-CAM Médio ({valid_heatmaps} Imagens Corretas)')
    plt.axis('off')
    plt.colorbar()
    plt.show()
else:
    print("Não foi possível calcular o Grad-CAM médio.")

import sys
if 'google.colab' in sys.modules:
  !pip install lime

from lime import lime_image
from skimage.segmentation import mark_boundaries

explainer = lime_image.LimeImageExplainer()

num_samples_to_plot = len(sample_images)
fig, axes = plt.subplots(num_samples_to_plot, 3, figsize=(15, 4 * num_samples_to_plot))

if num_samples_to_plot == 1:
    axes = np.expand_dims(axes, axis=0)

for i in range(num_samples_to_plot):
    img = sample_images[i]
    label = sample_labels[i]
    mask_img = sample_masks[i]

    explanation = explainer.explain_instance(
        img.astype('double'),
        model.predict,
        top_labels=3,
        hide_color=0,
        num_samples=500
    )

    preds = model.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        pred_class,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mask_img, cmap='gray')
    axes[i, 1].set_title('Máscara Real')
    axes[i, 1].axis('off')

    axes[i, 2].imshow(mark_boundaries(temp, mask))
    axes[i, 2].set_title('Explicação LIME')
    axes[i, 2].axis('off')

plt.tight_layout()
plt.show()

import shap
import matplotlib.pyplot as plt
import numpy as np

num_samples_to_plot = len(sample_images)
fig, axes = plt.subplots(1, num_samples_to_plot, figsize=(4 * num_samples_to_plot, 4))

if num_samples_to_plot == 1:
    axes = [axes]

for i in range(num_samples_to_plot):
    axes[i].imshow(sample_masks[i], cmap='gray')
    axes[i].set_title(f'Máscara Real (Amostra {i+1})')
    axes[i].axis('off')
plt.show()

background = []
for img, label in test_ds.unbatch().take(20):
    background.append(img.numpy())
background = np.array(background)

explainer_shap = shap.GradientExplainer(model, background)

shap_values = explainer_shap.shap_values(sample_images)

shap.image_plot(shap_values, sample_images)

import shap
import numpy as np

background = []
for img, label in test_ds.unbatch().take(20):
    background.append(img.numpy())
background = np.array(background)

explainer_shap = shap.GradientExplainer(model, background)

shap_values = explainer_shap.shap_values(sample_images)

shap.image_plot(shap_values, sample_images)

def load_and_preprocess_with_mask(img_path, mask_path, label):
    full_img_path = tf.strings.join([BASE_PATH, img_path])
    img = tf.io.read_file(full_img_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0

    def apply_mask():
        full_mask_path = tf.strings.join([BASE_PATH, mask_path])
        mask = tf.io.read_file(full_mask_path)
        mask = tf.image.decode_image(mask, channels=1, expand_animations=False)
        mask = tf.image.resize(mask, IMG_SIZE)
        mask_bin = tf.cast(mask > 0, tf.float32)

        red_color = tf.constant([1.0, 0.0, 0.0], dtype=tf.float32)
        overlay_img = tf.where(mask_bin > 0, red_color, img)
        return overlay_img

    def return_original():
        return img

    has_mask = tf.math.not_equal(mask_path, '-')

    final_img = tf.cond(has_mask, apply_mask, return_original)

    return final_img, label

def create_masked_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((
        dataframe['fullPath'].values,
        dataframe['Tumour_Contour'].values,
        dataframe['label'].values
    ))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess_with_mask, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("Criando Datasets com sobreposição de máscaras fortemente delineadas...")
train_ds_masked = create_masked_ds(train_df, shuffle=True)
val_ds_masked = create_masked_ds(val_df, shuffle=False)
test_ds_masked = create_masked_ds(test_df, shuffle=False)
print("Concluído!")

plt.figure(figsize=(12, 4))
for images, labels in train_ds_masked.take(1):
    for i in range(5):
        plt.subplot(1, 5, i+1)
        plt.imshow(images[i].numpy())
        label_name = list(class_map.keys())[list(class_map.values()).index(labels[i].numpy())]
        plt.title(f'Label: {label_name}')
        plt.axis('off')
plt.tight_layout()
plt.show()

print("Iniciando o treinamento do modelo com máscaras sobrepostas...")

base_model_masked = applications.ResNet50(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model_masked.trainable = True

model_masked = models.Sequential([
    base_model_masked,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model_masked.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint_masked = callbacks.ModelCheckpoint('best_model_masked.keras', save_best_only=True, monitor='val_loss')

history_masked = model_masked.fit(
    train_ds_masked,
    validation_data=val_ds_masked,
    epochs=50,
    callbacks=[checkpoint_masked]
)

test_loss_masked, test_acc_masked = model_masked.evaluate(test_ds_masked)
print(f'\nAcurácia no Teste (Treinamento com máscaras): {test_acc_masked:.4f}')
print(f'Acurácia no Teste (Treinamento sem máscaras - Original): {test_acc:.4f}')

y_pred_probs_masked = model_masked.predict(test_ds_masked)
y_pred_masked = np.argmax(y_pred_probs_masked, axis=1)

print("\nRelatório de Classificação (Treinamento com máscaras):")
print(classification_report(y_true, y_pred_masked, target_names=target_names))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_masked.history['accuracy'], label='Train Acc')
plt.plot(history_masked.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento com máscaras)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_masked.history['loss'], label='Train Loss')
plt.plot(history_masked.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento com máscaras)')
plt.legend()
plt.show()

cm_masked = confusion_matrix(y_true, y_pred_masked)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_masked, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento com máscaras)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

import cv2
import numpy as np

valid_samples_masked = test_df[(test_df['Status'] != 'Normal') & (test_df['Tumour_Contour'] != '-')]
num_samples_masked = min(20, len(valid_samples_masked))
sample_df_masked = valid_samples_masked.sample(num_samples_masked, random_state=SEED)

sample_ds_masked = create_masked_ds(sample_df_masked, shuffle=False)

sample_images_masked = []
sample_labels_masked = []

for images, labels in sample_ds_masked.unbatch().take(num_samples_masked):
    sample_images_masked.append(images.numpy())
    sample_labels_masked.append(labels.numpy())

sample_images_masked = np.array(sample_images_masked)
sample_labels_masked = np.array(sample_labels_masked)

print(f'Selecionadas {len(sample_images_masked)} imagens com máscaras sobrepostas para explicação (excluindo Normais).')

num_samples_to_plot = len(sample_images_masked)
fig, axes = plt.subplots(num_samples_to_plot, 2, figsize=(10, 4 * num_samples_to_plot))

if num_samples_to_plot == 1:
    axes = np.expand_dims(axes, axis=0)

for i in range(num_samples_to_plot):
    img = sample_images_masked[i]
    img_batch = np.expand_dims(img, 0)

    try:
        heatmap = get_gradcam_plus_plus(model_masked, img_batch, 'conv5_block3_out')
        heatmap_resized = cv2.resize(heatmap, IMG_SIZE)

        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Imagem com Máscara (Classe Real: {sample_labels_masked[i]})')
        axes[i, 0].axis('off')

        axes[i, 1].imshow(img)
        axes[i, 1].imshow(heatmap_resized, alpha=0.5, cmap='jet')
        axes[i, 1].set_title('Grad-CAM++')
        axes[i, 1].axis('off')
    except Exception as e:
        print(f'Erro no Grad-CAM++ para amostra {i}: {e}')

plt.tight_layout()
plt.show()

explainer_masked = lime_image.LimeImageExplainer()

num_samples_to_plot = len(sample_images_masked)
fig, axes = plt.subplots(num_samples_to_plot, 2, figsize=(10, 4 * num_samples_to_plot))

if num_samples_to_plot == 1:
    axes = np.expand_dims(axes, axis=0)

for i in range(num_samples_to_plot):
    img = sample_images_masked[i]
    label = sample_labels_masked[i]

    explanation = explainer_masked.explain_instance(
        img.astype('double'),
        model_masked.predict,
        top_labels=3,
        hide_color=0,
        num_samples=500
    )

    preds = model_masked.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        pred_class,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mark_boundaries(temp, mask))
    axes[i, 1].set_title('Explicação LIME')
    axes[i, 1].axis('off')

plt.tight_layout()
plt.show()

import shap
import warnings
import numpy as np
warnings.filterwarnings('ignore')

# 1. Obter um conjunto de background para o modelo com máscara
background_masked = []
for img, label in test_ds_masked.unbatch().take(20):
    background_masked.append(img.numpy())
background_masked = np.array(background_masked)

# 2. SHAP GradientExplainer para o model_masked com o background correto
explainer_shap_masked = shap.GradientExplainer(model_masked, background_masked)

# 3. Calcular os valores SHAP
shap_values_masked = explainer_shap_masked.shap_values(sample_images_masked)

print("Valores SHAP para o modelo com máscaras:")
shap.image_plot(shap_values_masked, sample_images_masked)

import shap
import numpy as np
import warnings
warnings.filterwarnings('ignore')

background_masked = []
for img, label in test_ds_masked.unbatch().take(20):
    background_masked.append(img.numpy())
background_masked = np.array(background_masked)

explainer_shap_masked = shap.GradientExplainer(model_masked, background_masked)

shap_values_masked = explainer_shap_masked.shap_values(sample_images_masked)

print("Valores SHAP para o modelo com máscaras:")
shap.image_plot(shap_values_masked, sample_images_masked)

def load_and_preprocess_with_crop(img_path, mask_path, label):
    full_img_path = tf.strings.join([BASE_PATH, img_path])
    img = tf.io.read_file(full_img_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)
    img_float = tf.cast(img, tf.float32) / 255.0

    def apply_crop():
        full_mask_path = tf.strings.join([BASE_PATH, mask_path])
        mask = tf.io.read_file(full_mask_path)
        mask = tf.image.decode_image(mask, channels=1, expand_animations=False)
        mask_bin = tf.cast(mask > 0, tf.int32)

        rows = tf.reduce_any(mask_bin > 0, axis=[1, 2])
        cols = tf.reduce_any(mask_bin > 0, axis=[0, 2])

        row_indices = tf.where(rows)
        col_indices = tf.where(cols)

        def valid_bbox():
            rmin = tf.cast(row_indices[0][0], tf.int32)
            rmax = tf.cast(row_indices[-1][0], tf.int32)
            cmin = tf.cast(col_indices[0][0], tf.int32)
            cmax = tf.cast(col_indices[-1][0], tf.int32)

            pad = tf.constant(10, dtype=tf.int32)
            rmin = tf.maximum(0, rmin - pad)
            rmax = tf.minimum(tf.shape(img)[0], rmax + pad)
            cmin = tf.maximum(0, cmin - pad)
            cmax = tf.minimum(tf.shape(img)[1], cmax + pad)

            cropped_img = tf.image.crop_to_bounding_box(img_float, rmin, cmin, rmax - rmin, cmax - cmin)
            return tf.image.resize(cropped_img, IMG_SIZE)

        def invalid_bbox():
            return tf.image.resize(img_float, IMG_SIZE)

        return tf.cond(tf.logical_and(tf.size(row_indices) > 0, tf.size(col_indices) > 0), valid_bbox, invalid_bbox)

    def return_original():
        return tf.image.resize(img_float, IMG_SIZE)

    has_mask = tf.math.not_equal(mask_path, '-')
    final_img = tf.cond(has_mask, apply_crop, return_original)

    final_img.set_shape([*IMG_SIZE, CHANNELS])
    return final_img, label

def create_cropped_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((
        dataframe['fullPath'].values,
        dataframe['Tumour_Contour'].values,
        dataframe['label'].values
    ))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess_with_crop, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("Criando Datasets com recorte (crop) da máscara...")
train_ds_cropped = create_cropped_ds(train_df, shuffle=True)
val_ds_cropped = create_cropped_ds(val_df, shuffle=False)
test_ds_cropped = create_cropped_ds(test_df, shuffle=False)
print("Concluído!")

plt.figure(figsize=(12, 4))
for images, labels in train_ds_cropped.take(1):
    for i in range(5):
        plt.subplot(1, 5, i+1)
        plt.imshow(images[i].numpy())
        label_name = list(class_map.keys())[list(class_map.values()).index(labels[i].numpy())]
        plt.title(f'Label: {label_name}')
        plt.axis('off')
plt.tight_layout()
plt.show()

print("Iniciando o treinamento do modelo com imagens recortadas (crop)...")

base_model_cropped = applications.ResNet50(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model_cropped.trainable = True

model_cropped = models.Sequential([
    base_model_cropped,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model_cropped.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint_cropped = callbacks.ModelCheckpoint('best_model_cropped.keras', save_best_only=True, monitor='val_loss')

history_cropped = model_cropped.fit(
    train_ds_cropped,
    validation_data=val_ds_cropped,
    epochs=50,
    callbacks=[checkpoint_cropped]
)

test_loss_cropped, test_acc_cropped = model_cropped.evaluate(test_ds_cropped)
print(f'\nAcurácia no Teste (Treinamento com crop): {test_acc_cropped:.4f}')

y_pred_probs_cropped = model_cropped.predict(test_ds_cropped)
y_pred_cropped = np.argmax(y_pred_probs_cropped, axis=1)

print("\nRelatório de Classificação (Treinamento com crop):")
print(classification_report(y_true, y_pred_cropped, target_names=target_names))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_cropped.history['accuracy'], label='Train Acc')
plt.plot(history_cropped.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento com crop)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_cropped.history['loss'], label='Train Loss')
plt.plot(history_cropped.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento com crop)')
plt.legend()
plt.show()

cm_cropped = confusion_matrix(y_true, y_pred_cropped)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_cropped, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento com crop)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

sample_ds_cropped = create_cropped_ds(sample_df_masked, shuffle=False)

sample_images_cropped = []
sample_labels_cropped = []

for images, labels in sample_ds_cropped.unbatch().take(len(sample_df_masked)):
    sample_images_cropped.append(images.numpy())
    sample_labels_cropped.append(labels.numpy())

sample_images_cropped = np.array(sample_images_cropped)
sample_labels_cropped = np.array(sample_labels_cropped)

print(f'Selecionadas {len(sample_images_cropped)} imagens recortadas para explicação.')

num_samples_to_plot = len(sample_images_cropped)
fig, axes = plt.subplots(num_samples_to_plot, 2, figsize=(10, 4 * num_samples_to_plot))

if num_samples_to_plot == 1:
    axes = np.expand_dims(axes, axis=0)

for i in range(num_samples_to_plot):
    img = sample_images_cropped[i]
    img_batch = np.expand_dims(img, 0)

    try:
        heatmap = get_gradcam_plus_plus(model_cropped, img_batch, 'conv5_block3_out')
        heatmap_resized = cv2.resize(heatmap, IMG_SIZE)

        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Imagem Recortada (Classe Real: {sample_labels_cropped[i]})')
        axes[i, 0].axis('off')

        axes[i, 1].imshow(img)
        axes[i, 1].imshow(heatmap_resized, alpha=0.5, cmap='jet')
        axes[i, 1].set_title('Grad-CAM++')
        axes[i, 1].axis('off')
    except Exception as e:
        print(f'Erro no Grad-CAM++ para amostra {i}: {e}')

plt.tight_layout()
plt.show()

explainer_cropped = lime_image.LimeImageExplainer()

num_samples_to_plot = len(sample_images_cropped)
fig, axes = plt.subplots(num_samples_to_plot, 2, figsize=(10, 4 * num_samples_to_plot))

if num_samples_to_plot == 1:
    axes = np.expand_dims(axes, axis=0)

for i in range(num_samples_to_plot):
    img = sample_images_cropped[i]
    label = sample_labels_cropped[i]

    explanation = explainer_cropped.explain_instance(
        img.astype('double'),
        model_cropped.predict,
        top_labels=3,
        hide_color=0,
        num_samples=500
    )

    preds = model_cropped.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        pred_class,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mark_boundaries(temp, mask))
    axes[i, 1].set_title('Explicação LIME')
    axes[i, 1].axis('off')

plt.tight_layout()
plt.show()

background_cropped = []
for img, label in test_ds_cropped.unbatch().take(20):
    background_cropped.append(img.numpy())
background_cropped = np.array(background_cropped)

explainer_shap_cropped = shap.GradientExplainer(model_cropped, background_cropped)
shap_values_cropped = explainer_shap_cropped.shap_values(sample_images_cropped)

print("Valores SHAP para o modelo com recorte:")
shap.image_plot(shap_values_cropped, sample_images_cropped)