# -*- coding: utf-8 -*-
"""fase 4 - implementação ajustada densenet121 + xai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzRGDuoOkJT9BFe9cvRcjTfw6ho_PHBD
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, applications
from sklearn.model_selection import GroupShuffleSplit
from google.colab import drive

drive.mount('/content/drive')

BASE_PATH = '/content/drive/MyDrive/MINI-DDSM/'
EXCEL_PATH = os.path.join(BASE_PATH, 'DataWMask.xlsx')
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
CHANNELS = 3
SEED = 42

df = pd.read_excel(EXCEL_PATH)

df['fullPath'] = df['fullPath'].str.replace('\\', '/', regex=False)
df['Tumour_Contour'] = df['Tumour_Contour'].str.replace('\\', '/', regex=False)

def extract_patient_id(path):
    parts = path.split('/')
    return parts[1] if len(parts) > 1 else 'unknown'

df['patient_id'] = df['fullPath'].apply(extract_patient_id)

class_map = {'Normal': 0, 'Benign': 1, 'Cancer': 2}
df['label'] = df['Status'].map(class_map)

gss_test = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
train_val_idx, test_idx = next(gss_test.split(df, df['label'], groups=df['patient_id']))

train_val_df = df.iloc[train_val_idx]
test_df = df.iloc[test_idx]

gss_val = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
train_idx, val_idx = next(gss_val.split(train_val_df, train_val_df['label'], groups=train_val_df['patient_id']))

train_df = train_val_df.iloc[train_idx]
val_df = train_val_df.iloc[val_idx]

print(f'Treino: {len(train_df)} | Val: {len(val_df)} | Teste: {len(test_df)}')

def increase_brightness(image):
    return np.clip(image * 1.2, 0.0, 1.0)

def load_and_preprocess(path, label):
    full_path = tf.strings.join([BASE_PATH, path])
    img = tf.io.read_file(full_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0

    img = tf.numpy_function(increase_brightness, [img], tf.float32)
    img.set_shape([224, 224, 3])

    return img, label

def create_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((dataframe['fullPath'].values, dataframe['label'].values))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

train_ds = create_ds(train_df)
val_ds = create_ds(val_df, shuffle=False)
test_ds = create_ds(test_df, shuffle=False)

base_model = applications.DenseNet121(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model.trainable = True

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint = callbacks.ModelCheckpoint('best_model.keras', save_best_only=True, monitor='val_loss')

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=50,
    callbacks=[checkpoint]
)

import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento sem máscaras)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento sem máscaras)')
plt.legend()
plt.show()

test_loss, test_acc = model.evaluate(test_ds)
print(f'\nAcurácia no Teste (Sem máscaras): {test_acc:.4f}')

print("\nCalculando métricas detalhadas...")
y_true = np.concatenate([y for x, y in test_ds], axis=0)
y_pred_probs = model.predict(test_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\nRelatório de Classificação (Treinamento sem máscaras):")
target_names = ['Normal', 'Benign', 'Cancer']
print(classification_report(y_true, y_pred, target_names=target_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento sem máscaras)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

import cv2
import numpy as np

def get_gradcam_plus_plus(model, img_array, last_conv_layer_name, target_class=None):
    base_model = model.layers[0]
    last_conv_layer = base_model.get_layer(last_conv_layer_name)
    res_output = last_conv_layer.output

    x = model.layers[1](base_model.output)
    for layer in model.layers[2:]:
        x = layer(x)

    grad_model = tf.keras.models.Model([base_model.input], [res_output, x])

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        if target_class is None:
            class_idx = tf.argmax(predictions[0])
        else:
            class_idx = target_class
        loss = predictions[:, class_idx]

    grads = tape.gradient(loss, conv_outputs)
    weights = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap = tf.reduce_sum(tf.multiply(weights, conv_outputs), axis=-1)

    heatmap = np.maximum(heatmap, 0) / (np.max(heatmap) + 1e-10)
    return heatmap[0]

def calculate_iou(y_true, y_pred):
    intersection = np.logical_and(y_true, y_pred)
    union = np.logical_or(y_true, y_pred)
    if np.sum(union) == 0: return 0
    return np.sum(intersection) / np.sum(union)

test_with_masks = test_df[(test_df['Status'] != 'Normal') & (test_df['Tumour_Contour'] != '-')]
correct_samples = []

print("Buscando 20 imagens corretas no conjunto de TESTE...")
for i, row in test_with_masks.iterrows():
    img_path = os.path.join(BASE_PATH, row['fullPath'])
    img_raw = tf.io.read_file(img_path)
    img_decoded = tf.image.decode_jpeg(img_raw, channels=3)
    img_resized = tf.image.resize(img_decoded, IMG_SIZE)
    img_normalized = tf.cast(img_resized, tf.float32) / 255.0
    img_batch = tf.expand_dims(img_normalized, 0)

    pred = model.predict(img_batch, verbose=0)
    if np.argmax(pred[0]) == row['label']:
        correct_samples.append((row, img_normalized))
    if len(correct_samples) == 20:
        break

if len(correct_samples) > 0:
    fig, axes = plt.subplots(len(correct_samples), 3, figsize=(15, 4 * len(correct_samples)))
    if len(correct_samples) == 1:
        axes = np.expand_dims(axes, axis=0)

    avg_heatmap = np.zeros(IMG_SIZE)

    for i, (row, img_normalized) in enumerate(correct_samples):
        mask_path = os.path.join(BASE_PATH, row['Tumour_Contour'])
        img_batch = tf.expand_dims(img_normalized, 0)

        try:
            heatmap = get_gradcam_plus_plus(model, img_batch, 'relu', target_class=row['label'])

            mask_img = cv2.imread(mask_path, 0)
            if mask_img is not None:
                mask = cv2.resize(mask_img, IMG_SIZE) > 0

                heatmap_np = heatmap.numpy() if hasattr(heatmap, 'numpy') else heatmap
                heatmap_resized = cv2.resize(heatmap_np, IMG_SIZE)

                avg_heatmap += heatmap_resized
                heatmap_bin = heatmap_resized > 0.5
                iou_score = calculate_iou(mask, heatmap_bin)

                axes[i, 0].imshow(img_normalized)
                axes[i, 0].set_title(f'Original ({row["Status"]})')
                axes[i, 0].axis('off')

                axes[i, 1].imshow(mask, cmap='gray')
                axes[i, 1].set_title('Máscara Real')
                axes[i, 1].axis('off')

                axes[i, 2].imshow(img_normalized)
                axes[i, 2].imshow(heatmap_resized, alpha=0.5, cmap='jet')
                axes[i, 2].set_title(f'Grad-CAM++ (IoU: {iou_score:.4f})')
                axes[i, 2].axis('off')
        except Exception as e:
            print(f'Erro na amostra {i+1}: {e}')

    plt.tight_layout()
    plt.show()

    avg_heatmap /= len(correct_samples)
    plt.figure(figsize=(6,6))
    plt.imshow(avg_heatmap, cmap='jet')
    plt.title(f'Grad-CAM Médio ({len(correct_samples)} imagens - Teste)')
    plt.axis('off')
    plt.show()
else:
    print('Nenhuma amostra correta com máscara encontrada no conjunto de teste.')

import numpy as np
import matplotlib.pyplot as plt
import cv2

sample_df = test_df[(test_df['Status'] != 'Normal') & (test_df['Tumour_Contour'] != '-')].sample(20, random_state=SEED)

sample_images = []
sample_labels = []
sample_masks = []

for _, row in sample_df.iterrows():
    img_path = os.path.join(BASE_PATH, row['fullPath'])
    img_raw = tf.io.read_file(img_path)
    img_decoded = tf.image.decode_jpeg(img_raw, channels=3)
    img_resized = tf.image.resize(img_decoded, IMG_SIZE)
    img_normalized = tf.cast(img_resized, tf.float32) / 255.0
    sample_images.append(img_normalized.numpy())
    sample_labels.append(row['label'])

    mask_path = os.path.join(BASE_PATH, row['Tumour_Contour'])
    mask_raw = cv2.imread(mask_path, 0)
    if mask_raw is not None:
        mask_resized = cv2.resize(mask_raw, IMG_SIZE)
    else:
        mask_resized = np.zeros(IMG_SIZE)
    sample_masks.append(mask_resized)

sample_images = np.array(sample_images)
sample_labels = np.array(sample_labels)
sample_masks = np.array(sample_masks)
print(f'Selecionadas {len(sample_images)} imagens com máscaras para explicação.')

import sys
if 'google.colab' in sys.modules:
  !pip install lime

from lime import lime_image
from skimage.segmentation import mark_boundaries

explainer = lime_image.LimeImageExplainer()

fig, axes = plt.subplots(20, 3, figsize=(15, 80))
for i in range(20):
    img = sample_images[i]
    label = sample_labels[i]
    mask_img = sample_masks[i]

    explanation = explainer.explain_instance(
        img.astype('double'),
        model.predict,
        labels=(1, 2),
        hide_color=0,
        num_samples=500
    )

    preds = model.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        label,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mask_img, cmap='gray')
    axes[i, 1].set_title('Máscara Real')
    axes[i, 1].axis('off')

    axes[i, 2].imshow(mark_boundaries(temp, mask))
    axes[i, 2].set_title(f'LIME (Classe {label}) - Prós/Contras')
    axes[i, 2].axis('off')

plt.tight_layout()
plt.show()

import shap
import matplotlib.pyplot as plt

fig, axes = plt.subplots(4, 5, figsize=(20, 16))
axes = axes.flatten()
for i in range(20):
    axes[i].imshow(sample_masks[i], cmap='gray')
    axes[i].set_title(f'Máscara Real (Amostra {i+1})')
    axes[i].axis('off')
plt.tight_layout()
plt.show()

background_images, _ = next(iter(train_ds.take(1)))

explainer_shap = shap.GradientExplainer(model, background_images)
shap_values = explainer_shap.shap_values(sample_images)

shap_values_sem_normal = [shap_values[1], shap_values[2]]

print("Explicabilidade SHAP (Excluindo a classe Normal):")
shap.image_plot(shap_values_sem_normal, sample_images)

def load_and_preprocess_with_mask(img_path, mask_path, label):
    full_img_path = tf.strings.join([BASE_PATH, img_path])
    img = tf.io.read_file(full_img_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0

    def apply_mask():
        full_mask_path = tf.strings.join([BASE_PATH, mask_path])
        mask = tf.io.read_file(full_mask_path)
        mask = tf.image.decode_image(mask, channels=1, expand_animations=False)
        mask = tf.image.resize(mask, IMG_SIZE)
        mask_bin = tf.cast(mask > 0, tf.float32)

        overlay_r = tf.where(mask_bin[:,:,0] > 0, 1.0, img[:,:,0])
        overlay_g = tf.where(mask_bin[:,:,0] > 0, 0.0, img[:,:,1])
        overlay_b = tf.where(mask_bin[:,:,0] > 0, 0.0, img[:,:,2])

        overlay_img = tf.stack([overlay_r, overlay_g, overlay_b], axis=-1)
        return overlay_img

    def return_original():
        return img

    has_mask = tf.math.not_equal(mask_path, '-')
    final_img = tf.cond(has_mask, apply_mask, return_original)

    return final_img, label

def create_masked_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((
        dataframe['fullPath'].values,
        dataframe['Tumour_Contour'].values,
        dataframe['label'].values
    ))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess_with_mask, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("Criando Datasets com sobreposição de máscaras bem delineadas...")
train_ds_masked = create_masked_ds(train_df, shuffle=True)
val_ds_masked = create_masked_ds(val_df, shuffle=False)
test_ds_masked = create_masked_ds(test_df, shuffle=False)
print("Concluído!")

plt.figure(figsize=(12, 4))
for images, labels in train_ds_masked.take(1):
    for i in range(5):
        plt.subplot(1, 5, i+1)
        plt.imshow(images[i].numpy())
        label_name = list(class_map.keys())[list(class_map.values()).index(labels[i].numpy())]
        plt.title(f'Label: {label_name}')
        plt.axis('off')
plt.tight_layout()
plt.show()

print("Iniciando o treinamento do modelo com máscaras sobrepostas...")

base_model_masked = applications.DenseNet121(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model_masked.trainable = True

model_masked = models.Sequential([
    base_model_masked,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model_masked.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint_masked = callbacks.ModelCheckpoint('best_model_masked.keras', save_best_only=True, monitor='val_loss')

history_masked = model_masked.fit(
    train_ds_masked,
    validation_data=val_ds_masked,
    epochs=50,
    callbacks=[checkpoint_masked]
)

import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_masked.history['accuracy'], label='Train Acc')
plt.plot(history_masked.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento com máscaras)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_masked.history['loss'], label='Train Loss')
plt.plot(history_masked.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento com máscaras)')
plt.legend()
plt.show()

test_loss_masked, test_acc_masked = model_masked.evaluate(test_ds_masked)
print(f'\nAcurácia no Teste (Treinamento com máscaras): {test_acc_masked:.4f}')
print(f'Acurácia no Teste (Original, sem máscaras): {test_acc:.4f}')

print("\nCalculando métricas detalhadas...")
y_pred_probs_masked = model_masked.predict(test_ds_masked)
y_pred_masked = np.argmax(y_pred_probs_masked, axis=1)

print("\nRelatório de Classificação (Treinamento com máscaras):")
print(classification_report(y_true, y_pred_masked, target_names=target_names))

cm_masked = confusion_matrix(y_true, y_pred_masked)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_masked, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento com máscaras)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

"""### Explicabilidade (XAI) para o Modelo com Máscaras
Vamos aplicar as mesmas técnicas (Grad-CAM++, LIME e SHAP) no novo modelo treinado para entender como a sobreposição da máscara afetou a tomada de decisão.
"""

import cv2
import numpy as np

sample_images_masked = []
sample_labels_masked = []

for images, labels in test_ds_masked.unbatch():
    if labels.numpy() != 0:
        sample_images_masked.append(images.numpy())
        sample_labels_masked.append(labels.numpy())

    if len(sample_images_masked) == 20:
        break

sample_images_masked = np.array(sample_images_masked)
sample_labels_masked = np.array(sample_labels_masked)

print(f'Selecionadas {len(sample_images_masked)} imagens com máscaras sobrepostas para explicação.')

fig, axes = plt.subplots(20, 2, figsize=(10, 80))

for i in range(20):
    img = sample_images_masked[i]
    img_batch = np.expand_dims(img, 0)

    try:
        heatmap = get_gradcam_plus_plus(model_masked, img_batch, 'relu', target_class=sample_labels_masked[i])
        heatmap_resized = cv2.resize(heatmap.numpy() if hasattr(heatmap, 'numpy') else heatmap, IMG_SIZE)

        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Imagem com Máscara (Classe Real: {sample_labels_masked[i]})')
        axes[i, 0].axis('off')

        axes[i, 1].imshow(img)
        axes[i, 1].imshow(heatmap_resized, alpha=0.5, cmap='jet')
        axes[i, 1].set_title('Grad-CAM++')
        axes[i, 1].axis('off')
    except Exception as e:
        print(f'Erro no Grad-CAM++ para amostra {i}: {e}')

plt.tight_layout()
plt.show()

explainer_masked = lime_image.LimeImageExplainer()

fig, axes = plt.subplots(20, 2, figsize=(10, 80))
for i in range(20):
    img = sample_images_masked[i]
    label = sample_labels_masked[i]

    explanation = explainer_masked.explain_instance(
        img.astype('double'),
        model_masked.predict,
        labels=(1, 2),
        hide_color=0,
        num_samples=500
    )

    preds = model_masked.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        label,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mark_boundaries(temp, mask))
    axes[i, 1].set_title(f'LIME (Classe {label}) - Prós/Contras')
    axes[i, 1].axis('off')

plt.tight_layout()
plt.show()

import shap
import warnings
warnings.filterwarnings('ignore')

background_images_masked, _ = next(iter(train_ds_masked.take(1)))

explainer_shap_masked = shap.GradientExplainer(model_masked, background_images_masked)
shap_values_masked = explainer_shap_masked.shap_values(sample_images_masked)

shap_values_masked_sem_normal = [shap_values_masked[1], shap_values_masked[2]]

print("Valores SHAP para o modelo com máscaras (Excluindo a classe Normal):")
shap.image_plot(shap_values_masked_sem_normal, sample_images_masked)

def load_and_preprocess_with_crop(img_path, mask_path, label):
    full_img_path = tf.strings.join([BASE_PATH, img_path])
    img = tf.io.read_file(full_img_path)
    img = tf.image.decode_jpeg(img, channels=CHANNELS)

    def apply_crop():
        full_mask_path = tf.strings.join([BASE_PATH, mask_path])
        mask = tf.io.read_file(full_mask_path)
        mask = tf.image.decode_image(mask, channels=1, expand_animations=False)
        mask_bin = tf.cast(mask > 0, tf.int64)

        coords = tf.where(mask_bin[:,:,0] > 0)

        def do_crop():
            y_min = tf.reduce_min(coords[:, 0])
            y_max = tf.reduce_max(coords[:, 0])
            x_min = tf.reduce_min(coords[:, 1])
            x_max = tf.reduce_max(coords[:, 1])

            padding = tf.constant(30, dtype=tf.int64)

            img_h = tf.cast(tf.shape(img)[0], tf.int64)
            img_w = tf.cast(tf.shape(img)[1], tf.int64)

            y_min = tf.maximum(tf.constant(0, dtype=tf.int64), y_min - padding)
            y_max = tf.minimum(img_h, y_max + padding)
            x_min = tf.maximum(tf.constant(0, dtype=tf.int64), x_min - padding)
            x_max = tf.minimum(img_w, x_max + padding)

            y_min_i32 = tf.cast(y_min, tf.int32)
            y_max_i32 = tf.cast(y_max, tf.int32)
            x_min_i32 = tf.cast(x_min, tf.int32)
            x_max_i32 = tf.cast(x_max, tf.int32)

            cropped_img = img[y_min_i32:y_max_i32, x_min_i32:x_max_i32, :]
            return tf.image.resize(cropped_img, IMG_SIZE)

        def fallback():
            return tf.image.resize(img, IMG_SIZE)

        return tf.cond(tf.shape(coords)[0] > 0, do_crop, fallback)

    def return_original():
        return tf.image.resize(img, IMG_SIZE)

    has_mask = tf.math.not_equal(mask_path, '-')
    final_img = tf.cond(has_mask, apply_crop, return_original)

    final_img = tf.cast(final_img, tf.float32) / 255.0
    final_img.set_shape([224, 224, 3])

    return final_img, label

def create_crop_ds(dataframe, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((
        dataframe['fullPath'].values,
        dataframe['Tumour_Contour'].values,
        dataframe['label'].values
    ))
    if shuffle:
        ds = ds.shuffle(len(dataframe))
    ds = ds.map(load_and_preprocess_with_crop, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("Criando Datasets com recortes nas lesões...")
train_ds_crop = create_crop_ds(train_df, shuffle=True)
val_ds_crop = create_crop_ds(val_df, shuffle=False)
test_ds_crop = create_crop_ds(test_df, shuffle=False)
print("Concluído!")

plt.figure(figsize=(12, 4))
for images, labels in train_ds_crop.take(1):
    for i in range(5):
        plt.subplot(1, 5, i+1)
        plt.imshow(images[i].numpy())
        label_name = list(class_map.keys())[list(class_map.values()).index(labels[i].numpy())]
        plt.title(f'Label: {label_name}')
        plt.axis('off')
plt.tight_layout()
plt.show()

print("Iniciando o treinamento do modelo com imagens focadas (Crops)...")

base_model_crop = applications.DenseNet121(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model_crop.trainable = True

model_crop = models.Sequential([
    base_model_crop,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(3, activation='softmax')
])

model_crop.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

checkpoint_crop = callbacks.ModelCheckpoint('best_model_crop.keras', save_best_only=True, monitor='val_loss')

history_crop = model_crop.fit(
    train_ds_crop,
    validation_data=val_ds_crop,
    epochs=50,
    callbacks=[checkpoint_crop]
)

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_crop.history['accuracy'], label='Train Acc')
plt.plot(history_crop.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Treinamento com crop)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_crop.history['loss'], label='Train Loss')
plt.plot(history_crop.history['val_loss'], label='Val Loss')
plt.title('Loss (Treinamento com crop)')
plt.legend()
plt.show()

test_loss_crop, test_acc_crop = model_crop.evaluate(test_ds_crop)
print(f'\nAcurácia no Teste (Treinamento com crop): {test_acc_crop:.4f}')

print("\nCalculando métricas detalhadas...")
y_pred_probs_crop = model_crop.predict(test_ds_crop)
y_pred_crop = np.argmax(y_pred_probs_crop, axis=1)

print("\nRelatório de Classificação (Treinamento com crop):")
print(classification_report(y_true, y_pred_crop, target_names=target_names))

cm_crop = confusion_matrix(y_true, y_pred_crop)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_crop, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title('Matriz de Confusão (Treinamento com crop)')
plt.ylabel('Rótulo Real')
plt.xlabel('Previsão do Modelo')
plt.show()

sample_images_crop = []
sample_labels_crop = []

for images, labels in test_ds_crop.unbatch():
    if labels.numpy() != 0:
        sample_images_crop.append(images.numpy())
        sample_labels_crop.append(labels.numpy())

    if len(sample_images_crop) == 20:
        break

sample_images_crop = np.array(sample_images_crop)
sample_labels_crop = np.array(sample_labels_crop)

print(f'Selecionadas {len(sample_images_crop)} imagens cropadas para explicação.')

fig, axes = plt.subplots(20, 2, figsize=(10, 80))

for i in range(20):
    img = sample_images_crop[i]
    img_batch = np.expand_dims(img, 0)

    try:
        heatmap = get_gradcam_plus_plus(model_crop, img_batch, 'relu', target_class=sample_labels_crop[i])
        heatmap_resized = cv2.resize(heatmap.numpy() if hasattr(heatmap, 'numpy') else heatmap, IMG_SIZE)

        axes[i, 0].imshow(img)
        axes[i, 0].set_title(f'Imagem Cropada (Classe Real: {sample_labels_crop[i]})')
        axes[i, 0].axis('off')

        axes[i, 1].imshow(img)
        axes[i, 1].imshow(heatmap_resized, alpha=0.5, cmap='jet')
        axes[i, 1].set_title('Grad-CAM++ (Crop)')
        axes[i, 1].axis('off')
    except Exception as e:
        print(f'Erro no Grad-CAM++ para amostra {i}: {e}')

plt.tight_layout()
plt.show()

explainer_crop = lime_image.LimeImageExplainer()

fig, axes = plt.subplots(20, 2, figsize=(10, 80))
for i in range(20):
    img = sample_images_crop[i]
    label = sample_labels_crop[i]

    explanation = explainer_crop.explain_instance(
        img.astype('double'),
        model_crop.predict,
        labels=(1, 2),
        hide_color=0,
        num_samples=500
    )

    preds = model_crop.predict(np.expand_dims(img, axis=0))
    pred_class = np.argmax(preds)

    temp, mask = explanation.get_image_and_mask(
        label,
        positive_only=False,
        num_features=10,
        hide_rest=False
    )

    axes[i, 0].imshow(img)
    axes[i, 0].set_title(f'Real: {label} | Pred: {pred_class}')
    axes[i, 0].axis('off')

    axes[i, 1].imshow(mark_boundaries(temp, mask))
    axes[i, 1].set_title(f'LIME (Classe {label}) - Prós/Contras')
    axes[i, 1].axis('off')

plt.tight_layout()
plt.show()

background_images_crop, _ = next(iter(train_ds_crop.take(1)))

explainer_shap_crop = shap.GradientExplainer(model_crop, background_images_crop)
shap_values_crop = explainer_shap_crop.shap_values(sample_images_crop)

shap_values_crop_sem_normal = [shap_values_crop[1], shap_values_crop[2]]

print("Valores SHAP para o modelo com Crops (Excluindo a classe Normal):")
shap.image_plot(shap_values_crop_sem_normal, sample_images_crop)